services:
    Yamilovs\SypexGeo\SypexGeo:
        arguments:
            - "%faritslv_sypex_geo.database_path%"
            - "%faritslv_sypex_geo.mode%"
            -
    FaritSlv\Bundle\SypexGeoBundle\Command\GetIpDataCommand:
        arguments: ['@Yamilovs\SypexGeo\SypexGeo']
        tags:
            - { name: 'console.command', command: 'faritslv:sypex-geo:get-ip-data' }

    FaritSlv\Bundle\SypexGeoBundle\Command\UpdateDatabaseFileCommand:
        arguments:
            - '@filesystem'
            - '%faritslv_sypex_geo.database_path%'
            - '%faritslv_sypex_geo.connection%'
        tags:
            - { name: 'console.command', command: 'faritslv:sypex-geo:update-database-file' }
